ALTER TYPE "ShopItemType" ADD VALUE IF NOT EXISTS 'OUTFIT';
ALTER TYPE "ShopItemType" ADD VALUE IF NOT EXISTS 'COMPANION';
ALTER TYPE "ShopItemType" ADD VALUE IF NOT EXISTS 'AURA';
ALTER TYPE "EquipmentSlot" ADD VALUE IF NOT EXISTS 'OUTFIT';
ALTER TYPE "EquipmentSlot" ADD VALUE IF NOT EXISTS 'COMPANION';
ALTER TYPE "EquipmentSlot" ADD VALUE IF NOT EXISTS 'AURA';
ALTER TYPE "ItemRarity" ADD VALUE IF NOT EXISTS 'LEGENDARY';
ALTER TYPE "ItemRarity" ADD VALUE IF NOT EXISTS 'MYTHIC';
